<a href="https://colab.research.google.com/github/maryb2002/Exploring-NumPy-Operations/blob/main/NumpyOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import numpy as np

print(np.__version__)

1.23.5


In [ ]:
array_1d = np.arange(10)

print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
random_vector = np.random.rand(10)

max_index = np.argmax(random_vector)
random_vector[max_index] = 0

print("Random vector with the maximum value replaced by 0:")
print(random_vector)

Random vector with the maximum value replaced by 0:
[0.76639787 0.44334041 0.24000294 0.49405456 0.         0.70872987
 0.48237594 0.1249378  0.78833911 0.01153059]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

number_to_find = 8
indices = np.where(arr == number_to_find)

print("Indices of the number 8:")
print(indices)

found_value = arr[indices]
print("The number 8 is at position:", indices[0], indices[1])
print("Value at that position:", found_value)

Indices of the number 8:
(array([1]), array([2]))
The number 8 is at position: [1] [2]
Value at that position: [8]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

subset = arr[2:5]

print("The numbers [3, 4, 5] from the array:")
print(subset)

The numbers [3, 4, 5] from the array:
[3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

a = arr[-4:]

print("The last 4 numbers from the array:")
print(a)

The last 4 numbers from the array:
[4 5 6 7]


In [ ]:
t = np.ones((2, 2), dtype=bool)

print(t)

[[ True  True]
 [ True  True]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

odd_numbers = arr[arr % 2 == 1]

print("Odd numbers from the array:")
print(odd_numbers)

Odd numbers from the array:
[1 3 5 7 9]


In [ ]:
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
vector = np.arange(10, 50)

reversed_vector = vector[::-1]

print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
random_array = np.random.randint(0, 101, size=(10, 10))

min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random Array:")
print(random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Random Array:
[[ 93  74  77  91  99  34  25  48   2  92]
 [ 90  75  76   6  71  13  51   6  42  49]
 [ 52   3  35  41  11  59  63  78   1  86]
 [ 31  90  25  40  80  54  26  44  83  48]
 [ 27  47  37  30  14  45  10  66  13  97]
 [ 90  89  91  19  82  50  31  89  32  29]
 [ 73  76  28  44  86  46  89  45  85  90]
 [ 35  56  38  60   3  15  98 100  45  60]
 [ 54  32  15  33  25  96  36  78   1  55]
 [ 96  60  75  59  23  68  31  79  88  89]]
Minimum Value: 1
Maximum Value: 100


In [ ]:
randon = np.random.rand(3, 3, 3)

print(randon)

[[[0.72625862 0.95446903 0.81838454]
  [0.41225191 0.69147558 0.49916902]
  [0.21475657 0.47552144 0.13823194]]

 [[0.59685572 0.08907355 0.94865203]
  [0.29700216 0.97187806 0.62227297]
  [0.89253023 0.51253688 0.45368651]]

 [[0.41375129 0.59459249 0.03301919]
  [0.83044448 0.37814465 0.72246247]
  [0.22883711 0.54263957 0.86027384]]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1

print("Modified array with odd numbers replaced by -1:")
print(arr)

Modified array with odd numbers replaced by -1:
[-1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
float_array = np.array([1.3, 2.5, 3.7, 4.2])
print(float_array)

[1.3 2.5 3.7 4.2]


In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr_2d = arr_1d.reshape(2, -1)

print("1D Array:")
print(arr_1d)

print("2D Array with 2 rows:")
print(arr_2d)

1D Array:
[1 2 3 4 5 6 7 8]
2D Array with 2 rows:
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
common_values = np.intersect1d(Z1, Z2)

print("Array Z1:", Z1)
print("Array Z2:", Z2)
print("Common values:", common_values)

Array Z1: [9 6 3 3 6 2 8 2 2 2]
Array Z2: [6 3 1 1 5 6 9 0 8 8]
Common values: [3 6 8 9]


In [ ]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are A and B equal?", are_equal)

Array A: [0 0 0 1 0]
Array B: [0 1 1 0 0]
Are A and B equal? False


In [ ]:
a = np.array([0, 2, 5])
b = np.array([0, 2, 5])
stacked_array = np.vstack((a, b))

print("Array a:")
print(a)

print("Array b:")
print(b)

print("Stacked array (vertically):")
print(stacked_array)

Array a:
[0 2 5]
Array b:
[0 2 5]
Stacked array (vertically):
[[0 2 5]
 [0 2 5]]


In [ ]:
a = np.array([0, 2, 5])
b = np.array([0, 2, 5])
stacked_array = np.hstack((a, b))

print("Array a:")
print(a)

print("Array b:")
print(b)

print("Stacked array (horizontally):")
print(stacked_array)

Array a:
[0 2 5]
Array b:
[0 2 5]
Stacked array (horizontally):
[0 2 5 0 2 5]


In [ ]:
tmp = np.arange(15)
mask = (tmp >= 5) & (tmp <= 10)
result = tmp[mask]

print("Array tmp:")
print(tmp)

print("Items between 5 and 10:")
print(result)

Array tmp:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Items between 5 and 10:
[ 5  6  7  8  9 10]


In [ ]:
def pair_max(a, b):
    """Get the element-wise maximum of two arrays a and b."""
    return np.maximum(a, b)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print(result)

[6 7 9 8 9 7 5]


In [ ]:
arr = np.arange(9).reshape(3, 3)
print("Original array:")
print(arr)
arr[:, [1, 2]] = arr[:, [2, 1]]

print("Array after swapping columns 1 and 2:")
print(arr)

Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array after swapping columns 1 and 2:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
random_array = np.random.uniform(5, 10, size=(5, 3))
print(random_array)

[[5.78587404 6.50345848 5.38143376]
 [7.25235658 7.33681963 7.28473441]
 [6.6692437  5.68738312 9.02319587]
 [9.57774524 9.95388847 7.02586235]
 [5.24585111 9.53064721 9.74516757]]
